### ISSUE TITLE
Is there a way to let the GM customize "Esoteric Lore"

### ISSUE THREAD

**Issue by rectulo** [mysurvive/pf2e-thaum-vuln#10]
For other languages, it would be better to let the GM chose the name of the Lore used :
In french Esoteric Lore is called Connaissances ésotériques.

Is there a way to ask the user by which name the Esoteric lore will be replaced in the language they use in the settings ?

**Comment by mysurvive** [comment]
This is a good question. I don't have another language environment set up for foundry so I can't check for myself. If you have a lore skill named "Connaissances ésotériques," does it roll correctly with your charisma modifier? The issue isn't what the skill is called, the issue is making a proper Esoteric Lore skill roll. The system automates a skill named "Esoteric Lore" to correctly _not_ use the intelligence modifier and instead use the charisma modifier instead.

**Comment by rectulo** [comment]
No, it won't work I think, unless fix it using rule elements.
I know the dev of the systems are working with lore skills. 
I think a good way to deal with Lore could be to give each identified lore skill an UUID and place them into a compendium to grant them with backgrounds and maybe fix requirements when they are needed in rule elements.

**Comment by mysurvive** [comment]
Unfortunately, until the skill is translated in the system and rolls properly, I can't do anything about the naming of the lore skill. I'm sorry about that. Once lore skills get some attention, I can revisit it. It shouldn't be a difficult change once it's working in core.
