### ISSUE TITLE
Other characters can benefit from EV/PA

### ISSUE THREAD

**Issue by Battelkrusr** [mysurvive/pf2e-thaum-vuln#39]
As far as I can tell EV/PA work by giving the target a weakness to whatever damage type the Thaumaturge is doing whenever they make an attack roll. However, that weakness persists beyond the Thaumaturges turn and other creatures can also benefit from it if they happen to do the same damage type as the Thaum. Is that supposed to happen? Is there a way around this?
My foundry version is 11.302, addon version is 0.11.2

**Comment by mysurvive** [comment]
What version of PF2e are you on? Is there a GM logged in at the same time? There are a few people that have reported this but I am not able to replicate it locally.

**Comment by mysurvive** [comment]
Proof that I'm not just trying to pawn off the issue 😅 : 
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/16602055/134a5815-0688-487f-a894-cd203eb66f35)
this is on my hosted foundry server that gets the module the same way everyone else does. Are there any console errors? (assuming there's a GM present as well)

**Comment by Battelkrusr** [comment]
PF2e is on version 5.0.2. I am the GM, and I did some more testing today, and for some reason, it worked. Yesterday, I was testing together with my thaumaturge player, with me rolling attacks and damage for the third party of the EV target, and the third party benefited from EV. Today, I got one of my non-thaumaturge players to roll attacks/damage for the third party, and it worked just fine. I rolled as the third party myself afterwards, and it still worked. I'm not sure if I just did something wrong yesterday(Combat was ongoing, the game was not paused, it was the attackers turn), if me rolling as the GM before any other players rolled messed something up, or if it was something unrelated. Either way, it appears to work now. If it crops up again, I'll do more testing and see what I can find.

**Comment by mysurvive** [comment]
That's so strange, one of the other folks having the issue said theirs started working today too. Obviously, I didn't push out any updates or anything. Very strange...

**Comment by yannou38** [comment]
Reopening this, sorry.

I made test on my own as i can reliably reproduce the issue here on my game.

When using the exploit weakness macro, here is the added RE of the effect :
{"key":"Weakness","type":"physical","value":6,"predicate":["target:mark:personal-antithesis-effect",{"or":["item:type:weapon","item:trait:unarmed"]}]}

which looks okay. However, when the thaum does an attack, the RE is replaced by 
{"key":"Weakness","type":"bludgeoning","value":"6","predicate":[],"slug":null}

which has no predicate, thus allowing the barbarian to benefit too.
