### ISSUE TITLE
Can't Manage Implements, none item I drag to the box works

### ISSUE THREAD

**Issue by Bomberman1988** [mysurvive/pf2e-thaum-vuln#41]
And therefore I can't use the macros that require the Implements

**Comment by Suldrun45** [comment]
After a few messages with Bomberman, it seems that the issue occurs when you delete from your inventory an item that has been flagged as implement.
If, after deleting such an item, you try to "Manage Implements", when you validate, you get the following error in the console:
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/49712710/61c69c7e-a127-4d49-be92-39d607b50bc3)

From what I can tell, when you delete the item, since the selectedImplements array still references the item, when the deleteImpEffects method loops on the implements, since the impl itself is undefined, impl.toObjet() crashes.

**Comment by mysurvive** [comment]
select the token and run `_token.actor.unsetFlag("pf2e-thaum-vuln","selectedImplements"). I will have a button that will do that in a future release.
