### ISSUE TITLE
Manage Implements button doesn't work

### ISSUE THREAD

**Issue by yannou38** [mysurvive/pf2e-thaum-vuln#43]
Updated the module recently, saw the new button to assign implements but clicking on it doesn't work, with a console erorr message.
The character is level 8 and existed before using the module, a new level 1 thaum seem to work properly

Uncaught (in promise) TypeError: imp is null

**Comment by Darshyne** [comment]
Same for me here is the error :
implements.js:33 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'grantedId')
[Detected 1 package: pf2e-thaum-vuln]
    at manageImplements (implements.js:33:49)
    at HTMLButtonElement.<anonymous> (hooks.js:195:7)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by mysurvive** [comment]
Two things that could cause this, either select the token and run `_token.actor.unsetFlag("pf2e-thaum-vuln","selectedImplements")`
If that doesn't work, level to 0 and then back up. You have to let the system do the leveling automation rather than dragging and dropping an implement feat on the sheet.

**Comment by mysurvive** [comment]
The latest release has error checking for these types of issues and will either handle the errors automatically or guide you on how to fix them.
