### ISSUE TITLE
Issue running macro

### ISSUE THREAD

**Issue by caelstuffs** [mysurvive/pf2e-thaum-vuln#50]
Hello! I am currently attempting to make the macro work for a thaumaturge in my game, but cannot seem to get it to run. Whenever I run the macro with the thaumaturge selected and an enemy targeted, I get the error message "controlled actor does not have an item with the id fodJ3zuwQsYnBbtk". Their implement has been selected and I have tried with both Mirror and Amulet implements configured, with no change in error message or missing item ID given.

For the sake of completeness, I will also note that the error was originally on a character who had been imported via Wanderer's Guide - however, the issue occurs even on an entirely new PC made in foundry alone.

**Comment by mysurvive** [comment]
What version of pf2e are you on?

**Comment by caelstuffs** [comment]
The latest update! I think I have also literally _just_ figured this out - the issue seems to be that I was trying to run the exploit vulnerability _action_ the searchbar gives you, rather than the macro from the compendium. Things seem to work just fine with the macro now that we went through the process of removing and manually adding the thaumaturge class back to the original imported character

**Comment by mysurvive** [comment]
Yep, "fodJ3zuwQsYnBbtk" is the tail end of the SourceID for exploit vulnerability (the action). In one of the 5.x updates, the SourceIDs all changed because of pack folders, that's why I was wondering what version you were on (perhaps there was some weird versioning mismatch). 

I'm not sure which searchbar you mean, but the module does allow you to click the exploit vulnerability action on your character sheet, where it will put the chat card in the chat and it appends a button to the bottom which will allow you to run the macro from there as well. I just verified this works as well.

**Comment by caelstuffs** [comment]
The search function for the compendium - the issue appears to happen when I drag the action itself from the results in the compendium to my macro bar and attempt to run it from there. having just checked, you are correct that everything functions normally when running the action as listed in the actual character sheet!
![Screenshot 2023-08-06 150828](https://github.com/mysurvive/pf2e-thaum-vuln/assets/61198908/fb0ef653-da36-4a42-ac8d-e787b1d99622)

**Comment by mysurvive** [comment]
Ah! I see! Yep either run the macro directly or send the EV action to the chat and hit the button. Glad it's working!
