### ISSUE TITLE
Breached Defenses not working on a success

### ISSUE THREAD

**Issue by VicenarySolid** [mysurvive/pf2e-thaum-vuln#57]
Breached Defenses only working on crit, success is marked as none.
![photo_2023-08-24_18-34-44](https://github.com/mysurvive/pf2e-thaum-vuln/assets/22013052/dab4a0f8-6128-4c50-a9f7-fe5b0d2ddaeb)

**Comment by mysurvive** [comment]
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/16602055/0f6e8fd9-4232-4914-b932-64be410d637e)
This is working correctly, the Shanrigol Behemoth does not have a bypassable resistance (it only has resistance)
Here are the rules for Breached Defenses:
`You can find the one weak point in a creature's scales, wards, or armor to get past its resistances. When you succeed at Exploit Vulnerability, you learn about the highest of the creature's resistances that can be bypassed (for example, if the creature has resistance to physical damage except silver), if the creature has one. If you prefer, you can choose the following benefit instead of one of the usual two benefits from Exploit Vulnerability.`
This only works on a creature that has a weakness that can be bypassed (for example, if the Behemoth had resistance to piercing 10 except cold iron, or something of the like)
To verify that it wasn't acting strangely, I forced a crit success as well and verified that there is still no bypassable resistance caluclated:
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/16602055/5793aa44-0f0e-4673-82be-b0838dcc7c29)

**Comment by mysurvive** [comment]
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/16602055/048812e2-ee05-4972-9c3c-0a4fd77bfd38)
This is working as intended, the Shanrigol Behemoth does not have a bypassable weakness, only normal weaknesses
Here are the rules for Breached Defenses:
`You can find the one weak point in a creature's scales, wards, or armor to get past its resistances. When you succeed at Exploit Vulnerability, you learn about the highest of the creature's resistances that can be bypassed (for example, if the creature has resistance to physical damage except silver), if the creature has one. If you prefer, you can choose the following benefit instead of one of the usual two benefits from Exploit Vulnerability.`
This means that a creature must have a weakness that can be bypassed in order to use breached defenses (for example, if it had resistant to piercing 10 except cold iron, or something like that)
I checked by forcing a critical success and received the same result:
![image](https://github.com/mysurvive/pf2e-thaum-vuln/assets/16602055/c358ecce-9616-43f0-9e0e-ccc7482a9ff9)
If you have differing results between a success and a crit success please let me know, but it looks like they are the same on my end.

**Comment by mysurvive** [comment]
It seems like you might be conflating two different features

Breached Defenses says that you can *only* bypass a resistance that has an exception to it. For example, "resistance to piercing 10 except silver" - this means if you have a regular dagger, you subtract 10 from the damage roll. If it is silvered, it bypasses the resistance entirely dealing the full damage. This is the Thaumaturge "swiss army knife" allowing you to hit normally where there would be a resistance without having the required materials (in this case, without having a silvered dagger). Nothing about Breached Defenses says *anything* about knowing what the resistances are, that's in the purview of Exploit Vulnerability.

Exploit Vulnerability says that on a critical success, you learn about all of the creature's resistances, weaknesses, and immunities. That's why you're seeing this on a critical success. On a normal success, you *only* learn about it's highest weakness, but not about its other weaknesses, resistances, or immunities.

So yes, this is working correctly.
