### ISSUE TITLE
Manage Implements button returns error

### ISSUE THREAD

**Issue by killersquirrel59** [mysurvive/pf2e-thaum-vuln#83]
I just got this mod so I'm not sure if this is just an issue of recent compatibility, but the Manage Implements button is not working as of v5.11.3. When I click it I get the following error message in the console:

There was an error managing implements. Press f12 to check the console for details.
fetch @ foundry.js:68326
notify @ foundry.js:68223
error @ foundry.js:68260
manageImplements @ implements.js:7
(anonymous) @ hooks.js:196
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by mysurvive** [comment]
Sounds like you used an importer, is that correct? If so, rebuild the character sheet within foundry only - no importers.

**Comment by killersquirrel59** [comment]
Ok. Good to know. Not worth using your mod if you don't want to spend an hour painfully making a character in Foundry's default system. I'll look elsewhere for my mods. It's far more valuable to me to not have to spend ages banging my head against this awful character creation system than have a couple automated effects. I only barely managed to convince my players to use Foundry at all because of the importer as all of them universally said the character creator was so bad it wasn't worth it. 

But none of that is your fault. If importers break your module, it just means it's not a good module for those of us who want to use importers. 

It would be useful if you included this as a warning on your documentation though.

**Comment by mysurvive** [comment]
Importers don't just break my module, they break the system itself. There isn't a single dev on the system or in any module that will recommend using an importer. 

You're coming at me with some hostility that I really don't know how to handle. I don't make money off of the module nor do I gain any form of notoriety or fame from it. I do it because Thaumaturge is actually terrible to run without it, and I have a thaumaturge one of the games I run. So, with all due respect (and I mean this truthfully, and respectfully), it doesn't make a difference to me one way or another whether you use my module or not. Adding that in was unnecessary and irrelevant. 

As for your comment about the system character creation, it's just P&P with a heavy amount of automation... I really don't understand how you're possibly "banging your head against this awful character creation system." It took my newbies a single day to figure out how to make a character on P&P and within 10 minutes, they had it ported over to Foundry.

I wish you the best of luck in your pathfinding.

**Comment by killersquirrel59** [comment]
I'm not hostile to you. I'm hostile to the developers of this terrible character building system that turned off my entire group from even being willing to try Foundry for months until we found Pathmuncher. You are not to blame in the slightest. I respect you and the work you and all the other modders do to help fix the limitations of this system immensely. I apologize if that came off as hostility to you. That was not at all my intent. 

It is not your responsibility to account for compatibility with other mods. I fully recognize that. It just means that your mods aren't useful to those who want to use importers. There's no value judgment on that, it's just a sad reality that users are forced into that choice when the character creation system is as unintuitive and clunky as it is. 

So thank you for your work and I'm sorry I can't use your mod. It looked like a really good one. I hope that many players who have the saint's patience needed to build characters in this system enjoy it immensely. Please keep up the good work for their sake. 

It would still be helpful if you included a line of text on the documentation page warning that it won't work with importers though if this is a known issue for your mod. I do use many other modules that are not broken by using an importer, and others that do break with an importer do often say so in their documentation.
